project:
  type: book
  output-dir: docs
  execute-dir: project
  render:
    - index.qmd
    - chapters/
    - exercises/
    - "!archive-source/"

book:
  title: "Quantitative Analysis of (Messy) Field Data"
  subtitle: "University of Wyoming -- ZOO-5500 (CRN 15229) | ECOL-5500 (CRN 15245)"
  sidebar:
    logo: graphics/jackalope_graphics/analytical_jackalope.png
    collapse-level: 1
  chapters:
    - part: "Course Overview"
      chapters:   
        - index.qmd
        - chapters/int_course_intro.qmd
        - chapters/int_syllabus.qmd
        - chapters/int_calendar_fa26.qmd
        - chapters/int_ai_policy.qmd  
        - chapters/int_assignment_grades.qmd

  # --- MAIN BODY ---
    - part: "Part ∅: Getting set up"
      chapters:   
        - chapters/int_preparing_yourself.qmd
        - chapters/int_project_scoping.qmd
        - chapters/00_ai_prompting.qmd
        #- chapters/00_using_jackalope_gpt.qmd

    - part: "Part I: Questions Before Models"
      chapters:
        - chapters/03_statistical_aphorisms.qmd
        - chapters/05_01_why_scms.qmd
        - chapters/01_hypotheses_estimands.qmd          
        - chapters/05_02_building_dags.qmd
        #- chapters/01_identification.qmd                # NEW
        #- chapters/01_identification_strategies.qmd     # NEW
        #- chapters/05_02b_KS_to_DAGs.qmd
        #- chapters/01_sem_vs_scm.qmd                    # NEW

    - part: "Part II: From the Causal System to Data"
      #chapters:
        #- chapters/01_nature_of_data.qmd
        #- chapters/01_data_orientation_audit.qmd        # NEW
        #- chapters/01_reproducible_workflow_intro.qmd
        #- chapters/01_metadata_low_friction.qmd
        #- chapters/01_naming_conventions.qmd
        #- chapters/02_data_exploration_intro.qmd
        #- chapters/02_data_exploration_toolkit.qmd
        #- chapters/02_outliers.qmd
        #- chapters/02_tutorial_data_exploration.qmd

    - part: "Part III: Models as Estimators"
      #chapters: 
        #- chapters/03_intro_modeling.qmd
        #- chapters/03_intro_glms.qmd
        #- chapters/03_tutorial_glms.qmd
        #- chapters/03_glm_partial_association.qmd
       # - chapters/03_DHARMA_diagnostics.qmd
       # - chapters/03_glmms.qmd
       # - chapters/03_tutorial_glmms_part01.qmd
       # - chapters/03_glmm_epilogue.qmd
       # - chapters/04_tutorial_gams.qmd

    - part: "Part IV: Estimating Causal Effects"
      #chapters:
        #- chapters/simple_scm.qmd
        #- chapters/SCM_part02.qmd
        #- chapters/brms_SCM.qmd

    - part: "Part V: Inference and Reporting"
      #chapters:
        #- chapters/06_inference_to_proposition.qmd       # NEW
        #- chapters/06_estimand_aware_workflow.qmd        # NEW
        #- chapters/final_report.qmd
    - part: "Final Report"
      #chapters:
        #- chapters/final_report_overview.qmd
format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    number-sections: true
    number-depth: 3
    css: styles.css
    code-copy: true
    
website:
  favicon: graphics/favicon/favicon.ico

editor: source
